name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
   runs-on: ubuntu-latest
   steps:
     - name: Autenticar no Docker Hub
       run: echo "Executando o comando Docker login"
     - name: Construcao da imagem docker
       run:  echo "Executando o comando Docker login"
     - name: Envio da imagem docker
       run:  echo "Executando o comando Docker login"
  cd:

  runs-on: ubuntu-latest
  steps:
     - name: Autenticar no AWs
       run: echo "Executando o comando aws configure"
     - name: Configurar kubectl
       run:  echo "Executando o comando aws eks update-kubeconfig"
     - name: Deplous os manifestos no kubernets
       run:  echo "Executando o comando kubectl apply"
