name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
   runs-on: ubuntu-latest
   steps:
     - name: Obeter o codigo do projeto
       uses: actions/checkout@v4

     - name: Login to Docker Hub.
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Debug GitHub Actions
       run: |
        echo "Secrets: ${{ secrets.DOCKERHUB_USERNAME }} - Token: ***"   

     - name: Build and push
       uses: docker/build-push-action@v6
       with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags:  |
            rodrigoavino/fake-shop:latest
            rodrigoavino/fake-shop:v${{github.run_number}}

  cd:
   runs-on: ubuntu-latest
   needs: [ci]
   steps:
     - name: Obeter o codigo do projeto
       uses: actions/checkout@v4

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

     - name: Configurar kubectl
       run:  echo "Executando o comando aws eks update-kubeconfig"
     - name: Deplous os manifestos no kubernets
       run:  echo "Executando o comando kubectl apply"
